connections:
  clickhouse: 
    host: 'pjhlc09pbp.us-east-1.aws.clickhouse.cloud'
    username: 'default'
    password: '995ubDA~PHRHp'
    port: 8443
models:
  openai:
    api_key: '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'
    params:
        temperature: 0
        model: 'text-davinci-003'