connections:
  clickhouse: 
    host: 'pjhlc09pbp.us-east-1.aws.clickhouse.cloud'
    username: 'default'
    password: ''
    port: 8443
models:
  openai:
    api_key: ''
    params:
        temperature: 0
        model: 'text-davinci-003'